Wrong domain key logging and writing config to disk
lootlocker/unity-sdk pull request #254
Opened 2024-05-13 08:07 UTC by AlmightyMikkel

The config written on disk is located in an Editor folder, which means it wont appear in builds.

2024-05-13 08:13 UTC, AndreasStokholm approved these changes
Only comments/thoughts: DiskLootLockerConfig.txt is a strange name imo. I would have gone with something like `PersistedLootLockerConfig` or similar personally.

Nothing that needs addressing, just a thought :D

2024-05-13 08:19 UTC, AlmightyMikkel commented
> Only comments/thoughts: DiskLootLockerConfig.txt is a strange name imo. I would have gone with something like `PersistedLootLockerConfig` or similar personally.
> 
> Nothing that needs addressing, just a thought :D

Ah yeah, I like that, it seems that the pr isnt good so I'll fix the name too :)

2024-05-15 09:46 UTC, kirre-bylund requested changes
I need a walkthrough of how this will work and look before I can approve. Also left a few comments on things I think we can improve.

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +                    string filePath = "Assets/LootLockerSDK/Resources/Config/Editor/PersistedLootLockerConfig.txt";
If we're writing to disk, then why not use something like .ini that is a standard for configuration?

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +                    string filePath = "Assets/LootLockerSDK/Resources/Config/Editor/PersistedLootLockerConfig.txt";
Also, here you hard code the file path but below you use Application.dataPath. These risk not being the same. Please settle for one.

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +            string fileDirectory = "Assets/LootLockerSDK/Resources/Config/Editor/";
We really should create these once statically I feel like and then just reuse the paths instead of typing it out like this every time.

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +            }
```suggestion
            if(!Directory.Exists(fileDirectory))
            {
                Directory.CreateDirectory(fileDirectory);
            } 
            
            if(!File.Exists(filePath))
            {
                File.Create(filePath).Close();
            }
```

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +using System.Linq;
Are you really using Linq?

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +#endif
I think I need to be taught how all this works. We have more settings than api key and domain key. Game version for example is a game breaking setting that needs to be persisted.

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +                    string filePath = "Assets/LootLockerSDK/Resources/Config/Editor/PersistedLootLockerConfig.txt";
Either that, or simply write LootLockerConfig as a serizialized json and then we can deserialize the object straight into an instance when reading?

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Editor/ProjectSettings.cs
> +                m_CustomSettings.FindProperty("domainKey").stringValue = gameSettings.domainKey;
From what I understand m_CustomSettings will be recreated from gameSettings next frame right? So why set this?

2024-05-15 09:46 UTC, kirre-bylund commented on Runtime/Game/Resources/LootLockerConfig.cs
> +                    Debug.LogWarning("You accidentally used the domain url instead of the domain key,\nWe took the domain key from the url.: " + domainkey);
I don't think we need to be explicit about this. They should figure it out when the input changes.

2025-04-22 07:24 UTC, closed without merging