Implement multiple progressions methods
LootLocker/unity-sdk pull request #80
Opened 2023-01-19 09:31 UTC by kristijan-ujevic

2023-01-19 09:43 UTC, JohannesLoot submitted a review, later dismissed
Awesome job!
👍

2023-01-19 11:05 UTC, kirre-bylund requested changes
Hmm, this sparks an interesting discussion on whether stuff we add should adhere to the current double layered (but superfluous) structure or not.

2023-01-19 11:05 UTC, kirre-bylund commented on Runtime/Game/LootLockerSDKManager.cs
> +            endpoint += "?";
Same thing about trailing characters

2023-01-19 11:20 UTC, kristijan-ujevic commented on Runtime/Client/LootLockerServerRequest.cs
> +    public class LootLockerPagination
I noticed that but didn't want to touch something else in this PR to keep it as atomic as possible. I think we should use this one in both cases.

2023-01-19 11:21 UTC, kristijan-ujevic commented on Runtime/Game/LootLockerSDKManager.cs
> +        /// <param name="after">How many extra rows after the players position</param>
This is copy pasta error, will fix :)

2023-01-19 11:22 UTC, kristijan-ujevic commented on Runtime/Game/LootLockerSDKManager.cs
> +        public static void GetAllPlayerProgressions(int count, string after, Action<LootLockerPaginatedPlayerProgressions> onComplete)
We are using ULID's as ID's on the backend

2023-01-19 11:22 UTC, kristijan-ujevic commented on Runtime/Game/LootLockerSDKManager.cs
> +            endpoint += "?";
yes, tested and it works, this is something I'd like to discuss with you guys

2023-01-19 11:23 UTC, kristijan-ujevic commented on Runtime/Game/LootLockerSDKManager.cs
> +                endpoint += $"after={after}&";
Same as above, we should discuss how to handle this, it works and the implementation is a lot cleaner by just adding the "&"

2023-01-19 11:23 UTC, kristijan-ujevic commented on Runtime/Game/LootLockerSDKManager.cs
> +        /// /// <param name="amount">Amount of points to be subtracted</param>
copy pasta error :)

2023-01-19 11:25 UTC, kristijan-ujevic commented on Runtime/Game/Requests/ProgressionsRequest.cs
> +        public string id { get; set; }
it is used for pagination

2023-01-19 11:25 UTC, kristijan-ujevic commented on Runtime/Game/Requests/ProgressionsRequest.cs
> +namespace LootLocker.Requests
Will do!

2023-01-19 11:26 UTC, kristijan-ujevic commented on Runtime/Game/Requests/ProgressionsRequest.cs
> +        public class LootLockerProgression
We should discuss this, I have a gripe LootLockerResponse too.

2023-01-19 11:28 UTC, kristijan-ujevic commented on Runtime/Game/Requests/ProgressionsRequest.cs
> +    public abstract class LLResponse
Leftover from testing, will remove :D

2023-01-24 07:28 UTC, kirre-bylund approved these changes
Looking good Ma Dude!

2023-01-27 07:55 UTC, kirre-bylund approved these changes

2023-02-13 14:30 UTC, closed without merging

2023-02-14 09:02 UTC, kirre-bylund commented
Replaced by https://github.com/LootLocker/unity-sdk/pull/94